#ifndef PARSER_H
#define PARSER_H

/* 
    This module handles the inputs of KWIC.
*/

#include<bits/stdc++.h>

using namespace std;

/* 
    Defines a template for the input module. 
    ParserModule consists of a list of words (stopwords or titles), and includes a method to print this list.
    (*) This list can be achieved based on different input formats, such as .txt or .xml, based on the selected mixing class.
*/
template <typename InputFormat>
class ParserModule : public InputFormat
{
    protected:
        // List generated by the input (specified by class InputFormat)
        list<string> list_input;
    
    public:        
        // Constructor - takes an input (file_name) and generate a list of words
        ParserModule(string file_name);

        // Prints the elements of the list.
        list<string> getListWords();
};

// Implements a mixing class that reads data from a .txt file.
class InputTXT
{   
    protected:
        list<string> list_words;
    
        list<string> generateListWords(string file_name);
};

/*
    A bibliographys essentially a parser module with an extra list, that consists of each title's words, separatedly.
    * extractWords() - This function implements a logic that breaks titles (a set of words) into individual words, that together compose a list.
*/
template <typename BibExtension>
class BibliographyManager : public BibExtension 
{     
    protected: 
        // Breaks a title into multiple words (including stop words)
        list<list<string>> extractWords(list<string> titles);

        // Each unit of the list corresponds to another list of words. This sub-list consists of all the words of a title, excluding the stop words.
        list<list<string>> titles_words;

    public:
        list<list<string>> getListTitlesWords();

        void setListTitlesWords(list<string> titles);
};

#endif